### ISSUE TITLE
Doesn't Appear to keep running

### ISSUE THREAD

**Issue by Cookietyrant** [dvgamerr/go-hoyolab#1]
I noticed I need to rerun this everyday in order for it to collect. I thought once it was ran it would become automatic.

**Comment by dvgamerr** [comment]
- use `Task Scheduler` and `Create Basic Task`
- select `When I log on` If you turn on Computer every day, or Select `Daily` If your run cumputer 24/7.

![image](https://user-images.githubusercontent.com/10203425/236996927-cb76c5be-09be-409c-8cb2-743bb0204d1a.png)

- after click Next select `Start a program`, Next and browse `hoyolab.exe`
- 
Thanks, I updated solution in README. https://github.com/dvgamerr/go-hoyolab#solution-for-automatic
